services:
  - type: web
    name: bus-tracking-app
    env: node
    plan: free
    buildCommand: |
      cd app_public
      npm install
      npm run build
      cd ..
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
