services:
  - type: web
    name: bus-tracking-app
    env: node
    plan: free
    runtime: node20
    buildCommand: |
      npm install
      cd app_public
      npm install
      npm run build
      cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
